### PR TITLE
Web curriculum

### PR DESCRIPTION
**Pull request by crymall**

### CODE REVIEW

**Comment by charlesdrews** [comment]
This is great! At a high level, I'd like to organize the topics around our 5-unit schedule, to make it easier to translate these standards into a curriculum map. 

I'll read thru more closely to see if I have any questions on the content - I'm no web expert, but maybe that's a good thing. If the standards make sense to me, they'll make sense to anyone :)

@mthorry @mottaquikarim @mmosayed @coreyladovsky @ckuang Please take a look at the specific content when you get a chance - look for any gaps or items you think can be cut out. Thank you!

**Comment by crymall** [comment]
@charlesdrews Totally, I hear ya. It was my aim to try to organize topics agnostic of timing in this document - I wanted to integrate it into a schedule later, but if that's not how the other standards docs are shaping up, I'm happy to edit / have others poke around here.

**Comment by mthorry** [comment]
Looks good so far @crymall! It seems like we've got all the content we need 💯

I agree with Charlie that splitting it into our units is a good idea because it will make ours lives _a lot_ easier when we're in the throes of planning and will leave less room for error (topics in the wrong unit, making sure we've covered all necessary topics for each unit, etc).

I would also break up any sections with a bunch of info listed within parenthesis or on one line into their own categories because each bullet has a lot of general info without many specifics. Something like: 
 - Data types are the different ways computers can store information. Data types in JS can include: 
   - integers: non-decimal numbers
   - booleans: represent relationships between entities as either true or false
   - etc..

In the same vein as that, it's also helpful to be more specific about exactly what the students will be expected to understand. The standards can be kind of like a fill-in-the-blank: "Students will be able to understand that ____". 
- General: "The difference between a CLI and a GUI"
- Specific: "A Command-Line Interface (CLI) is a way for a user to interact with a computer or program through the use of lines of text. A Graphical User Interface (GUI) is a way for a user to interact with a computer or program through items such as windows, icons, etc."

This makes it easier for us to come up with ways to assess if they actually understood what we meant for them to understand. Sorry for the information overload--happy to help out with this 😊

**Comment by coreyladovsky** [comment]
This is looking great. Do you think we should add some stuff on webpack?

**Pull request merged**
